import type { Product, Category } from "./types"

export const categories: Category[] = [
  { id: "pain-relief", name: "Pain Relief", icon: "pill" },
  { id: "cold-flu", name: "Cold & Flu", icon: "thermometer" },
  { id: "vitamins", name: "Vitamins & Supplements", icon: "vitamin" },
  { id: "first-aid", name: "First Aid", icon: "bandage" },
  { id: "diabetes", name: "Diabetes Care", icon: "activity" },
  { id: "personal-care", name: "Personal Care", icon: "spray" },
  { id: "baby-care", name: "Baby Care", icon: "baby" },
  { id: "devices", name: "Medical Devices", icon: "stethoscope" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Advanced Pain Relief",
    description:
      "Fast-acting pain relief for headaches, muscle pain, and minor arthritis. Contains acetaminophen 500mg.",
    price: 12.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "pain-relief",
    tags: ["pain relief", "headache", "muscle pain", "arthritis"],
    inStock: true,
    rating: 4.7,
    reviews: 128,
    prescription: false,
    dosage: "1-2 tablets every 4-6 hours as needed",
    sideEffects: ["Nausea", "Dizziness", "Upset stomach"],
    featured: true,
  },
  {
    id: "2",
    name: "Cold & Flu Relief",
    description: "Multi-symptom relief for cold and flu symptoms including congestion, cough, and fever.",
    price: 15.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "cold-flu",
    tags: ["cold", "flu", "congestion", "cough", "fever"],
    inStock: true,
    rating: 4.5,
    reviews: 96,
    prescription: false,
    dosage: "1 tablet every 4 hours",
    sideEffects: ["Drowsiness", "Dry mouth"],
    featured: true,
  },
  {
    id: "3",
    name: "Daily Multivitamin",
    description: "Complete daily vitamin with essential nutrients for overall health and immune support.",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "vitamins",
    tags: ["vitamins", "supplements", "immune support"],
    inStock: true,
    rating: 4.8,
    reviews: 215,
    prescription: false,
    dosage: "1 tablet daily with food",
    featured: true,
  },
  {
    id: "4",
    name: "First Aid Kit",
    description: "Comprehensive first aid kit with bandages, antiseptic wipes, gauze, and medical tape.",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "first-aid",
    tags: ["first aid", "bandages", "emergency"],
    inStock: true,
    rating: 4.9,
    reviews: 87,
    prescription: false,
  },
  {
    id: "5",
    name: "Blood Glucose Monitor",
    description: "Accurate and easy-to-use blood glucose monitoring system for diabetes management.",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "diabetes",
    tags: ["diabetes", "glucose", "monitor"],
    inStock: true,
    rating: 4.6,
    reviews: 132,
    prescription: false,
  },
  {
    id: "6",
    name: "Antibacterial Hand Sanitizer",
    description: "Kills 99.9% of germs without water. Contains 70% alcohol.",
    price: 5.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "personal-care",
    tags: ["sanitizer", "antibacterial", "hygiene"],
    inStock: true,
    rating: 4.4,
    reviews: 76,
    prescription: false,
  },
  {
    id: "7",
    name: "Baby Fever Reducer",
    description: "Gentle fever reducer and pain reliever for infants and children.",
    price: 9.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "baby-care",
    tags: ["baby", "fever", "pain relief"],
    inStock: true,
    rating: 4.8,
    reviews: 203,
    prescription: false,
    dosage: "Based on child's weight - see packaging",
  },
  {
    id: "8",
    name: "Digital Thermometer",
    description: "Fast and accurate digital thermometer with fever alert and memory function.",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "devices",
    tags: ["thermometer", "fever", "temperature"],
    inStock: true,
    rating: 4.7,
    reviews: 118,
    prescription: false,
  },
  {
    id: "9",
    name: "Allergy Relief",
    description: "24-hour non-drowsy allergy relief from indoor and outdoor allergies.",
    price: 17.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "cold-flu",
    tags: ["allergy", "antihistamine", "non-drowsy"],
    inStock: true,
    rating: 4.6,
    reviews: 89,
    prescription: false,
    dosage: "1 tablet daily",
    sideEffects: ["Dry mouth", "Headache"],
  },
  {
    id: "10",
    name: "Vitamin D3 Supplements",
    description: "Supports bone health and immune function with 2000 IU per softgel.",
    price: 13.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "vitamins",
    tags: ["vitamin D", "bone health", "immune support"],
    inStock: true,
    rating: 4.9,
    reviews: 156,
    prescription: false,
    dosage: "1 softgel daily",
  },
  {
    id: "11",
    name: "Blood Pressure Monitor",
    description: "Automatic upper arm blood pressure monitor with irregular heartbeat detection.",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "devices",
    tags: ["blood pressure", "heart health", "monitor"],
    inStock: true,
    rating: 4.5,
    reviews: 112,
    prescription: false,
  },
  {
    id: "12",
    name: "Antiseptic Wound Wash",
    description: "Gentle antiseptic solution for cleaning cuts, scrapes, and burns.",
    price: 8.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "first-aid",
    tags: ["antiseptic", "wound care", "first aid"],
    inStock: true,
    rating: 4.7,
    reviews: 64,
    prescription: false,
  },
  {
    id: "13",
    name: "Prescription Antibiotic",
    description: "Broad-spectrum antibiotic for bacterial infections. Requires prescription.",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "pain-relief",
    tags: ["antibiotic", "infection", "prescription"],
    inStock: true,
    rating: 4.8,
    reviews: 75,
    prescription: true,
    dosage: "As directed by physician",
    sideEffects: ["Nausea", "Diarrhea", "Rash"],
  },
  {
    id: "14",
    name: "Diabetic Test Strips",
    description: "Compatible test strips for blood glucose monitoring.",
    price: 34.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "diabetes",
    tags: ["diabetes", "test strips", "glucose"],
    inStock: true,
    rating: 4.6,
    reviews: 98,
    prescription: false,
  },
  {
    id: "15",
    name: "Baby Diaper Rash Cream",
    description: "Soothes and prevents diaper rash with zinc oxide formula.",
    price: 7.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "baby-care",
    tags: ["baby", "diaper rash", "skin care"],
    inStock: true,
    rating: 4.7,
    reviews: 142,
    prescription: false,
  },
  {
    id: "16",
    name: "Moisturizing Hand Cream",
    description: "Intensive moisturizing hand cream for dry, cracked skin.",
    price: 6.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "personal-care",
    tags: ["hand cream", "moisturizer", "dry skin"],
    inStock: true,
    rating: 4.5,
    reviews: 87,
    prescription: false,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((product) => product.category === categoryId)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery)),
  )
}
